[package]
name = "challenges"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fizzbuzz"
path = "proghum010723/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
